# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-26 10:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('awward', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='link',
            field=models.CharField(default=django.utils.timezone.now, max_length=3000),
            preserve_default=False,
        ),
    ]
