# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-26 17:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awward', '0002_project_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileMerch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pic', models.ImageField(null=True, upload_to='photos/')),
                ('username', models.CharField(max_length=40)),
                ('bio', models.CharField(max_length=3000)),
                ('projects', models.DecimalField(decimal_places=2, max_digits=20)),
            ],
        ),
    ]
