# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-11-01 07:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('awward', '0002_auto_20191031_2118'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rate',
            name='control',
        ),
        migrations.AddField(
            model_name='rate',
            name='avg',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='comment',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='total',
            field=models.IntegerField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
