# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-11-02 08:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awward', '0002_auto_20191102_0840'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='view_grade',
            field=models.IntegerField(null=True),
        ),
    ]
