# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-26 20:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awward', '0004_delete_profilemerch'),
    ]

    operations = [
        migrations.AddField(
            model_name='rate',
            name='content',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='rate',
            name='design',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='rate',
            name='usability',
            field=models.IntegerField(default=0),
        ),
    ]
