# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-31 07:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('awward', '0006_auto_20191030_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='upload_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='awward.Profile'),
        ),
    ]
